In [9]:
import numpy as np
# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(12)

def stepFunction(t):
    if t >= 0:
        return 1
    return 0

def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

# TODO: Fill in the code below to implement the perceptron trick.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
def perceptronStep(X, y, W, b, learn_rate = 0.01):
    # Fill in code
    for i in range(len(X)):
        y_hat = prediction(X[i],W,b)
        if y[i]-y_hat == 1:
            W[0] += X[i][0]*learn_rate
            W[1] += X[i][1]*learn_rate
            b += learn_rate
        elif y[i]-y_hat == -1:
            W[0] -= X[i][0]*learn_rate
            W[1] -= X[i][1]*learn_rate
            b -= learn_rate
    return W, b
    
# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2,1))
    #print(W.shape)
    #print(W)
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W, b = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
    return boundary_lines

import pandas as pd
data_df = pd.read_csv("PLA_data.csv",header=None)
X=np.array(data_df.iloc[:,0:2])
#print('X:',X.shape)
y=np.array(data_df[2])
trainPerceptronAlgorithm(X,y)

[(array([0.48362544]), array([-1.95449024])),
 (array([9.10277537]), array([-5.00100673])),
 (array([28.8600399]), array([-13.27174751])),
 (array([-263.48940357]), array([116.67013803])),
 (array([-25.4998568]), array([11.45662525])),
 (array([-15.40285747]), array([7.38857212])),
 (array([-11.54586438]), array([5.62391428])),
 (array([-9.17605628]), array([4.53967576])),
 (array([-7.54394054]), array([3.79543777])),
 (array([-6.37159103]), array([3.26085126])),
 (array([-5.53261374]), array([2.88431077])),
 (array([-4.86733724]), array([2.58572874])),
 (array([-4.53736477]), array([2.58376103])),
 (array([-4.13972129]), array([2.4008903])),
 (array([-3.79464524]), array([2.24219461])),
 (array([-3.49235898]), array([2.10317734])),
 (array([-3.2253682]), array([1.98039198])),
 (array([-2.98783215]), array([1.87115244])),
 (array([-2.77513141]), array([1.77333432])),
 (array([-2.58356455]), array([1.68523537])),
 (array([-2.41013085]), array([1.60547562])),
 (array([-2.25237202]), arra